### ISSUE TITLE
fix license conflict

### ISSUE THREAD

**Issue by RiedleroD** [necodeIT/lb_planner_plugin#21]
in LICENSE, it says CC-BY-NC-SA 4.0 International, while within the files it says GNU GPLv3.

I'm 90% sure that the actual license of most of the files is GPLv3. Since this is not the License I (nor I assume most contributors) intended their work to be, I suggest relicensing. Note that GLPv3 is not compatible with CC-BY-NC-SA, so we'll have to contact every other contributor to be able to relicense every file. Also note that GPLv3 states that it's not allowed to link it with files not licensed via GPLv3, so we're currently not upholding all terms of this license.

To relicense, we need explicit agreement from:
- [x] @RiedleroD 
- [x] @mcquenji 
- [x] @Muhiiii 

According to the git log, there's no other contributors.

**Comment by Muhiiii** [comment]
I hereby consent (i guess) lgtm :D

**Comment by RiedleroD** [comment]
fixed in:
- 4f3cd43c64daa5eaff79b18c22a6d621936215bf
- ebd6c4cf9f17a95742ebc820055c79346d88a1f9
- d9da5f5f6694411c8ce14549eb3e06e536e5939f
