### ISSUE TITLE
Get all modules should only return modules of enabled courses

### ISSUE THREAD

**Issue by mcquenji** [necodeIT/lb_planner_plugin#8]
`modules_get_all_modules` currently returns all modules of all courses the user is enrolled in. Instead it should only return tasks belonging to courses with `enabled` set to true

**Comment by RiedleroD** [comment]
![throwing_hands_up_crying](https://github.com/user-attachments/assets/ae2a3b50-19ae-43e3-9be8-a5596e85e1de)

**Comment by RiedleroD** [comment]
actually on second thought that should be fairly easy to implement

**Comment by RiedleroD** [comment]
![image](https://github.com/user-attachments/assets/2f881637-8205-4d6a-aafc-fa9c2ee8a32f)
lmao guess who fumbled the refactor (this is the opposite of what it should be)
